### ISSUE TITLE
Getting 404 message when trying to to view project

### ISSUE THREAD

**Issue by DMcP89** [emmgfx/emm-portfolio#1]
I have material design for coders installed and the plugin installed but when I make a new project and try to view it I get a 404 message.

**Comment by DMcP89** [comment]
same goes for preview.

**Comment by emmgfx** [comment]
I think that this may be a permalinks error. Try to go to the Settings / Permalinks in your wp-admin and save the settings without changes.

Tell me if it works 👍

**Comment by DMcP89** [comment]
That did the trick. What's the issue? Wordpress just doesn't recognize the posts?

**Comment by emmgfx** [comment]
I think that this is a Wordpress issue, (also, not entirely related with the theme or the plugin) because I had to do a few times with other themes and plugins.

I'm glad that it worked.
